#!/bin/sh

zr_output=
zr_previous=
for zr_argument in "$@"; do
  if test "$zr_previous" = -o; then
    zr_output=$zr_argument
    zr_previous=
  elif test "$zr_argument" = -o; then
    zr_previous=-o
  fi
done

# Use Tiger's runtime libraries, not compiler-rt objects built for newer macOS.
zr_link=yes
for zr_argument in "$@"; do
  case "$zr_argument" in
    -c|-S|-E|-M|-MM|-fsyntax-only|--version|-dump*|-print*) zr_link=no ;;
  esac
done
if test "$zr_link" = yes; then
  set -- "$@" -nodefaultlibs -lgcc_s.10.4 -lSystem
fi

/usr/bin/clang -arch i386 -mmacosx-version-min=10.4 "$@"
zr_status=$?

# Autoconf 2.13 executes target compiler probes even after a cross target was
# specified.  Prevent Rosetta from making those probes look like host tools.
if test $zr_status -eq 0; then
  case "$zr_output" in
    conftest|*/conftest) chmod a-x "$zr_output" ;;
  esac
fi

exit $zr_status
