# gmake
# This file is automatically generated for client.mk.
# To create a new .mozconfig file, you can visit,
#   http://webtools.mozilla.org/build/config.cgi

MOZ_OBJDIR=$(TOPSRCDIR)/../obj-retrozilla-linux
MOZ_MAKE_FLAGS=-j4
# --enable-application=browser is used by configure (not client.mk)
# --enable-default-toolkit=gtk2 is used by configure (not client.mk)
# --enable-optimize=-O2 is used by configure (not client.mk)
# --disable-debug is used by configure (not client.mk)
# --disable-tests is used by configure (not client.mk)
# --disable-installer is used by configure (not client.mk)
# --disable-updater is used by configure (not client.mk)
# --disable-gnomevfs is used by configure (not client.mk)
# --disable-dbus is used by configure (not client.mk)
# --without-system-jpg is used by configure (not client.mk)
# --without-system-zlib is used by configure (not client.mk)
# --enable-crypto is used by configure (not client.mk)
# --enable-svg is used by configure (not client.mk)
# --enable-canvas is used by configure (not client.mk)
