/* Modern generator suspension and legacy separation. MPL 1.1/GPL 2.0/LGPL 2.1. */
(function(){
var checks=0,failures=0;
function test(name,source){checks++;try{if(eval(source)===true)return;}catch(e){print('DETAIL '+name+': '+e);}failures++;print('FAIL generator '+name);}
function eq(r,v,d){return r.value===v&&r.done===d;}
test('lazy body','(function(){var n=0;function* g(){n++;yield 1}var i=g();return n===0&&eq(i.next(),1,false)&&n===1})()');
test('no yields','(function(){function* g(){return 3}return eq(g().next(),3,true)})()');
test('fallthrough clears yield value','(function(){var i=(function*(){yield 9})();i.next();return eq(i.next(),undefined,true)})()');
test('anonymous name is absent','!(function*(){}).hasOwnProperty("name")');
test('empty','eq((function*(){})().next(),undefined,true)');
test('sent values','(function(){function* g(){return yield 1}var i=g();return eq(i.next(9),1,false)&&eq(i.next(7),7,true)&&eq(i.next(),undefined,true)})()');
test('arguments','eq((function*(a){yield arguments[0]+a})(3).next(),6,false)');
test('strict unmapped arguments','eq((function*(a){"use strict";arguments[0]=9;yield a})(3).next(),3,false)');
test('rest unmapped arguments','eq((function*(a,...r){arguments[0]=9;yield a})(3).next(),3,false)');
test('bare yield conditional','(function(){var i=(function*(){(yield)?yield:yield})();i.next();return eq(i.next(),undefined,false)&&eq(i.next(),undefined,true)})()');
test('strict this','eq((function*(){"use strict";yield this}).call(null).next(),null,false)');
test('sloppy this','(function(){var o={};return eq((function*(){yield this}).call(o).next(),o,false)})()');
test('closed throw','(function(){var i=(function*(){})();i.next();try{i.throw(4)}catch(e){return e===4}return false})()');
test('closed return','(function(){var i=(function*(){})();i.next();return eq(i.return(4),4,true)})()');
test('newborn return','(function(){var n=0,i=(function*(){n++;try{yield 1}finally{n++}})();return eq(i.return(9),9,true)&&n===0})()');
test('newborn throw','(function(){var n=0,i=(function*(){n++;yield 1})();try{i.throw(9)}catch(e){return e===9&&n===0&&eq(i.next(),undefined,true)}return false})()');
test('throw caught','(function(){var i=(function*(){try{yield 1}catch(e){yield e}return 3})();return eq(i.next(),1,false)&&eq(i.throw(2),2,false)&&eq(i.next(),3,true)})()');
test('return finally yield','(function(){var i=(function*(){try{yield 1}finally{yield 2}})();i.next();return eq(i.return(8),2,false)&&eq(i.next(),8,true)})()');
test('return replaced in finally','(function(){var i=(function*(){try{yield 1}finally{yield 2;return 4}})();i.next();return eq(i.return(8),2,false)&&eq(i.next(),4,true)})()');
test('second return replaces first','(function(){var i=(function*(){try{yield 1}finally{yield 2}})();i.next();i.return(8);return eq(i.return(9),9,true)})()');
test('finally throw overrides return','(function(){var i=(function*(){try{yield 1}finally{yield 2;throw 4}})();i.next();i.return(8);try{i.next()}catch(e){return e===4}return false})()');
test('nested finally','(function(){var i=(function*(){try{try{yield 1}finally{yield 2}}finally{yield 3}})();i.next();return eq(i.return(8),2,false)&&eq(i.next(),3,false)&&eq(i.next(),8,true)})()');
test('reentry rejected','(function(){var i=(function*(){try{i.next()}catch(e){yield e instanceof TypeError}})();return eq(i.next(),true,false)})()');
test('nonconstructor','(function(){function* g(){}try{new g()}catch(e){return e instanceof TypeError}return false})()');
test('prototype chain','(function(){function* g(){}var p=Object.getPrototypeOf(g),i=g();return Object.getPrototypeOf(i)===g.prototype&&Object.getPrototypeOf(g.prototype)===p.prototype&&p.prototype.constructor===p&&Object.getPrototypeOf(p)===Function.prototype})()');
test('own prototype descriptor','(function(){function* g(){}var d=Object.getOwnPropertyDescriptor(g,"prototype");return d.writable&&!d.enumerable&&!d.configurable&&!g.prototype.hasOwnProperty("constructor")})()');
test('prototype override','(function(){function* g(){}var p={};g.prototype=p;return Object.getPrototypeOf(g())===p})()');
test('primitive prototype fallback','(function(){function* g(){}g.prototype=null;return Object.getPrototypeOf(g())===Object.getPrototypeOf(g).prototype})()');
test('iterator self','(function(){var i=(function*(){yield 1})();return i[Symbol.iterator]()===i})()');
test('tags','(function(){function* g(){}return Object.prototype.toString.call(g)==="[object GeneratorFunction]"&&Object.prototype.toString.call(g())==="[object Generator]"})()');
test('restricted metadata','(function(){function* g(){}if(g.hasOwnProperty("caller")||g.hasOwnProperty("arguments"))return false;try{g.caller}catch(e){return e instanceof TypeError}return false})()');
test('dynamic constructor','(function(){var G=Object.getPrototypeOf(function*(){}).constructor;return eq(G("a","yield a;return 7")(3).next(),3,false)&&eq(new G()().next(),undefined,true)})()');
test('dynamic constructor name','(function(){var G=Object.getPrototypeOf(function*(){}).constructor;return G().name==="anonymous"&&G.length===1})()');
test('decompile','(function(){var f=function* named(a){yield a;return 3};var g=eval("("+f.toString()+")");return eq(g(7).next(),7,false)})()');
test('for of generator','(function(){var a=[];for(var x of (function*(){yield 3;yield 4})())a.push(x);return a.join()==="3,4"})()');
test('for of break closes','(function(){var closed=0;for(var x of (function*(){try{yield 3}finally{closed++}})())break;return closed===1})()');
test('delegated values','(function(){var i=(function*(){return yield* [3,4]})();return eq(i.next(),3,false)&&eq(i.next(),4,false)&&eq(i.next(),undefined,true)})()');
test('delegated return value','(function(){var i=(function*(){return yield* (function*(){yield 3;return 4})()})();return eq(i.next(),3,false)&&eq(i.next(),4,true)})()');
test('delegated result identity','(function(){var result={value:3,done:false},src={};src[Symbol.iterator]=function(){return {next:function(){return result}}};return (function*(){yield* src})().next()===result})()');
test('delegated throw','(function(){var i=(function*(){return yield* (function*(){try{yield 1}catch(e){return e}})()})();i.next();return eq(i.throw(9),9,true)})()');
test('delegated return','(function(){var i=(function*(){return yield* (function*(){try{yield 1}finally{yield 2}})()})();i.next();return eq(i.return(9),2,false)&&eq(i.next(),9,true)})()');
test('delegated absent return','(function(){var src={};src[Symbol.iterator]=function(){return {next:function(){return {value:1}}}};var i=(function*(){yield* src;return 4})();i.next();return eq(i.return(9),9,true)})()');
test('delegated missing throw closes','(function(){var n=0,src={};src[Symbol.iterator]=function(){return {next:function(){return {value:1}},return:function(){n++;return {}}}};var i=(function*(){yield* src})();i.next();try{i.throw(9)}catch(e){return e instanceof TypeError&&n===1}return false})()');
test('delegated done false does not read value','(function(){var src={};src[Symbol.iterator]=function(){return {next:function(){return {done:false,get value(){throw 9}}}}};return (function*(){yield* src})().next().done===false})()');
test('yield star source','(function(){var f=function*(){yield* [3,4]};return eq(eval("("+f.toString()+")")().next(),3,false)})()');
test('generator method','eq(({*g(){yield 7}}).g().next(),7,false)');
test('computed generator method','(function(){var k="g",o={*[k](){yield 7}};return o.g.name==="g"&&eq(o.g().next(),7,false)})()');
test('method prototype','(function(){var o={*g(){yield 7}};return o.g.hasOwnProperty("prototype")&&!o.g.prototype.hasOwnProperty("constructor")})()');
test('ordinary nested yield identifier','eq((function*(){function f(yield){return yield}yield f(7)})().next(),7,false)');
test('yield commas','(function(){var i=(function*(){var x=(yield,3);return x})();return eq(i.next(),undefined,false)&&eq(i.next(),3,true)})()');
test('GC captures','(function(){var f,i=(function*(){let x={v:7};f=()=>x;yield 1;return x})();i.next();gc();return f().v===7&&eq(i.next(),f(),true)})()');
test('abandoned modern generator does not close','(function(){var n=0;var i=(function*(){try{yield 1}finally{n++}})();i.next();i=null;gc();gc();return n===0})()');
test('legacy generators preserved','(function(){var v=version();try{version(170);return evaluate("(function(){var i=(function(){yield 3;yield 4})();var a=i.next(),b=i.send(undefined);i.close();try{i.next()}catch(e){return a===3&&b===4&&e===StopIteration}return false})()") }finally{version(v)}})()');
test('sloppy declaration named yield','(function(){function* yield(){yield 3}return eq(yield().next(),3,false)})()');
test('nested expression named yield','eq((function*(){(function yield(){});yield 3})().next(),3,false)');
test('yield argument expression','(function(){function f(x){return x}var i=(function*(){return f(yield 3)})();i.next();return eq(i.next(7),7,true)})()');
test('yield star sent arguments','(function(){var a=[],src={};src[Symbol.iterator]=function(){return {next:function(v){a.push([arguments.length,v]);return {done:a.length===2,value:7}}}};var i=(function*(){return yield* src})();i.next(9);i.next(8);return a.length===2&&a[0][0]===1&&a[0][1]===undefined&&a[1][1]===8})()');
test('yield star return overrides body','(function(){var n=0,src={};src[Symbol.iterator]=function(){return {next:function(){return {value:1}},return:function(v){return {done:true,value:v+1}}}};var i=(function*(){try{yield* src;n++}finally{n+=2}})();i.next();return eq(i.return(8),9,true)&&n===2})()');
test('yield star return false resumes next','(function(){var a=[],src={};src[Symbol.iterator]=function(){return {next:function(v){a.push("next");return {value:v,done:a.length>1}},return:function(v){a.push("return");return {value:v,done:false}}}};var i=(function*(){return yield* src})();i.next();return eq(i.return(8),8,false)&&eq(i.next(9),9,true)&&a.join()==="next,return,next"})()');
test('yield star throw done true continues','(function(){var src={};src[Symbol.iterator]=function(){return {next:function(){return {value:1}},throw:function(v){return {done:true,value:v}}}};var i=(function*(){return (yield* src)+1})();i.next();return eq(i.throw(8),9,true)})()');
test('yield star missing throw close error','(function(){var src={};src[Symbol.iterator]=function(){return {next:function(){return {value:1}},return:function(){throw 7}}};var i=(function*(){yield* src})();i.next();try{i.throw(8)}catch(e){return e===7}return false})()');
test('yield star missing throw close primitive','(function(){var src={};src[Symbol.iterator]=function(){return {next:function(){return {value:1}},return:function(){return 7}}};var i=(function*(){yield* src})();i.next();try{i.throw(8)}catch(e){return e instanceof TypeError}return false})()');
test('yield star next getter reentry','(function(){var i,ok=false,src={};src[Symbol.iterator]=function(){return {get next(){try{i.next()}catch(e){ok=e instanceof TypeError}return function(){return {done:true}}}}};i=(function*(){yield* src})();return i.next().done&&ok})()');
test('yield star throw getter error','(function(){var src={};src[Symbol.iterator]=function(){return {next:function(){return {value:1}},get throw(){throw 7}}};var i=(function*(){yield* src})();i.next();try{i.throw(8)}catch(e){return e===7&&i.next().done}return false})()');
test('yield star done getter error caught','(function(){var src={};src[Symbol.iterator]=function(){return {next:function(){return {get done(){throw 7}}}}};var i=(function*(){try{yield* src}catch(e){yield e}yield 9})();return eq(i.next(),7,false)&&eq(i.next(),9,false)&&i.next().done})()');
test('yield star value getter error caught','(function(){var src={};src[Symbol.iterator]=function(){return {next:function(){return {done:true,get value(){throw 7}}}}};return eq((function*(){try{yield* src}catch(e){yield e}})().next(),7,false)})()');
test('generator return closes for of','(function(){var n=0,src={};src[Symbol.iterator]=function(){return {next:function(){return {value:1}},return:function(){n++;return {}}}};var i=(function*(){for(var v of src)yield v})();i.next();return eq(i.return(9),9,true)&&n===1})()');
test('generator return close error replaces return','(function(){var src={};src[Symbol.iterator]=function(){return {next:function(){return {value:1}},return:function(){throw 7}}};var i=(function*(){for(var v of src)yield v})();i.next();try{i.return(9)}catch(e){return e===7}return false})()');
test('suspended closure retains generator','(function(){var f;var i=(function*(){let x={v:7};yield ()=>x})();f=i.next().value;i=null;gc();gc();return f().v===7})()');
test('suspended arguments retain generator','(function(){var i=(function*(a){yield arguments;yield a})(3),a=i.next().value;i=null;gc();gc();return a[0]===3})()');
test('nested yield star','(function(){var i=(function*(){yield* (yield* (function*(){return yield 3})())})();return eq(i.next(),3,false)&&eq(i.next([4]),4,false)&&i.next().done})()');
['if(true) function* g(){}','label: function* g(){}','function* g(yield){}','function* g(a,a){}','var g=function* yield(){}','function* g(){var yield=3}','function* g(){yield*;}'].forEach(function(s){test('grammar '+s,'(function(){try{Function('+JSON.stringify(s)+');return false}catch(e){return e instanceof SyntaxError}})()');});
if(failures)throw Error('generator failures='+failures);
print('ES6-GENERATORS checks='+checks+' failures=0');
})();
