/* ES2015 module host regression. MPL 1.1/GPL 2.0/LGPL 2.1. */
function readModule(module,name){return namespaceModule(module)[name]}
var checks=0,failures=0;
function check(name,f){checks++;try{if(f()!==true)throw Error('wrong result')}catch(e){failures++;print('FAIL '+name+': '+e)}}
check('named live imports',function(){var a=compileModule('export let x=1;export function inc(){x++}'),b=compileModule('import {x,inc} from "a";export function read(){return x}export function change(){inc()}');linkModule(b,'a',a);evaluateModule(b);var read=readModule(b,'read'),change=readModule(b,'change');gc();if(read()!==1)return false;change();return read()===2});
check('default import',function(){var a=compileModule('export default function(){return 7}'),b=compileModule('import f from "a";export let n=f()');linkModule(b,'a',a);evaluateModule(b);return readModule(b,'n')===7});
check('renamed re-export',function(){var a=compileModule('export let x=3'),b=compileModule('export {x as y} from "a"'),c=compileModule('import {y} from "b";export let n=y');linkModule(b,'a',a);linkModule(c,'b',b);evaluateModule(c);return readModule(c,'n')===3});
check('star re-export',function(){var a=compileModule('export let x=3'),b=compileModule('export * from "a"'),c=compileModule('import {x} from "b";export let n=x');linkModule(b,'a',a);linkModule(c,'b',b);evaluateModule(c);return readModule(c,'n')===3});
check('re-export imported local',function(){var a=compileModule('export let x=3'),b=compileModule('import {x as y} from "a";export {y as z}'),c=compileModule('import {z} from "b";export let n=z');linkModule(b,'a',a);linkModule(c,'b',b);evaluateModule(c);return readModule(c,'n')===3});
check('cyclic functions',function(){var a=compileModule('import {readB} from "b";export let n=7;export function readA(){return n}export function read(){return readB()}'),b=compileModule('import {readA} from "a";export function readB(){return readA()}');linkModule(a,'b',b);linkModule(b,'a',a);evaluateModule(a);gc();return readModule(a,'read')()===7});
check('cyclic TDZ',function(){var a=compileModule('import {b} from "b";export let a=1'),b=compileModule('import {a} from "a";export let b=a');linkModule(a,'b',b);linkModule(b,'a',a);try{evaluateModule(a)}catch(e){return e instanceof ReferenceError}return false});
check('immutable imported binding',function(){var a=compileModule('export let x=3'),b=compileModule('import {x} from "a";export function write(){x=4}');linkModule(b,'a',a);evaluateModule(b);try{readModule(b,'write')()}catch(e){return e instanceof TypeError&&readModule(a,'x')===3}return false});
check('missing export rejected',function(){var a=compileModule('export let x=3'),b=compileModule('import {y} from "a"');linkModule(b,'a',a);try{evaluateModule(b)}catch(e){return e instanceof SyntaxError}return false});
check('ambiguous stars rejected',function(){var a=compileModule('export let x=3'),b=compileModule('export let x=4'),c=compileModule('export * from "a";export * from "b"'),d=compileModule('import {x} from "c"');linkModule(c,'a',a);linkModule(c,'b',b);linkModule(d,'c',c);try{evaluateModule(d)}catch(e){return e instanceof SyntaxError}return false});
check('explicit overrides stars',function(){var a=compileModule('export let x=3'),b=compileModule('export let x=4'),c=compileModule('export * from "a";export {x} from "b"'),d=compileModule('import {x} from "c";export let n=x');linkModule(c,'a',a);linkModule(c,'b',b);linkModule(d,'c',c);evaluateModule(d);return readModule(d,'n')===4});
check('default omitted from stars',function(){var a=compileModule('export default 3'),b=compileModule('export * from "a"'),c=compileModule('import x from "b"');linkModule(b,'a',a);linkModule(c,'b',b);try{evaluateModule(c)}catch(e){return e instanceof SyntaxError}return false});
check('evaluation order and once',function(){var a=compileModule('log.push("a")'),b=compileModule('import "a";log.push("b")'),c=compileModule('import "a";import "b";log.push("c")');this.log=[];linkModule(b,'a',a);linkModule(c,'a',a);linkModule(c,'b',b);evaluateModule(c);evaluateModule(c);return log.join()==='a,b,c'});
print('MODULE-LINK checks='+checks+' failures='+failures);if(failures)throw Error('module link failures');
