'use strict';
var checks=0;function check(v,m){checks++;if(!v)throw Error(m);}
var a={};Object.defineProperty(a,'first',{get:function(){return 1;},set:function(){},enumerable:true,configurable:true});a.second=2;
Object.defineProperty(a,'first',{set:function(v){gc();}});
check(Object.getOwnPropertyNames(a).join(',')==='first,second','replace accessor in place');
check(Object.keys(a).join(',')==='first,second','enumeration order');
Object.defineProperty(a,'first',{value:7,writable:true});gc();
check(Object.getOwnPropertyNames(a).join(',')==='first,second'&&a.first===7,'accessor to data');
Object.defineProperty(a,'first',{get:function(){return 9;}});gc();
check(Object.getOwnPropertyNames(a).join(',')==='first,second'&&a.first===9,'data to accessor');
var b={a:1,b:2,c:3,d:4};delete b.b;Object.defineProperty(b,'a',{enumerable:false});
check(Object.getOwnPropertyNames(b).join(',')==='a,c,d','middle deletion');
b.b=5;check(Object.getOwnPropertyNames(b).join(',')==='a,c,d,b','deleted property recreated last');
Object.defineProperty(b,'c',{get:function(){return 33;}});gc();
check(Object.getOwnPropertyNames(b).join(',')==='a,c,d,b'&&b.c===33,'replace after deletion and re-add');
var x=Symbol('x'),y=Symbol('y'),symbols={};symbols[x]=1;symbols[y]=2;Object.defineProperty(symbols,x,{enumerable:false});
check(Object.getOwnPropertySymbols(symbols)[0]===x&&Object.getOwnPropertySymbols(symbols)[1]===y,'symbol order');
var ar=[];ar.extra=1;Object.defineProperty(ar,'length',{value:2});
check(Object.getOwnPropertyNames(ar).join(',')==='length,extra','array length order');
var f=function(a,b){};f.extra=1;Object.defineProperty(f,'length',{enumerable:true});
check(Object.keys(f).join(',')==='length,extra','function metadata order');
var many={};for(var i=0;i<1000;i++)many['p'+i]=i;
for(i=0;i<100;i++)Object.defineProperty(many,'p'+i,{enumerable:false});gc();
var names=Object.getOwnPropertyNames(many);
check(names.length===1000&&names[0]==='p0'&&names[999]==='p999'&&many.p731===731,'large hash-backed object');
Object.seal(many);check(Object.getOwnPropertyNames(many).join(',')===names.join(','),'seal retains order');
var duplicate=Function('a','a','return a;');duplicate.extra=3;Object.defineProperty(duplicate,'length',{enumerable:true});
check(duplicate(1,2)===2&&Object.keys(duplicate).join(',')==='length,extra','duplicate parameters retain hidden scope ordering');
var watched={a:1,b:2},seen=0;watched.watch('a',function(id,old,v){seen++;return v;});Object.defineProperty(watched,'a',{enumerable:false});watched.a=8;watched.unwatch('a');
check(seen===1&&watched.a===8&&Object.getOwnPropertyNames(watched).join(',')==='a,b','watchpoint replacement');
var source={get a(){Object.defineProperty(source,'b',{enumerable:false});gc();return 1;},b:2,c:3};
var assigned=Object.assign({},source);
check(Object.keys(assigned).join(',')==='a,c'&&Object.getOwnPropertyNames(source).join(',')==='a,b,c','enumeration after getter descriptor mutation');
var changing={get a(){Object.defineProperty(changing,'a',{value:7,configurable:true});gc();return 1;},b:2};
check(changing.a===1&&changing.a===7&&Object.getOwnPropertyNames(changing).join(',')==='a,b','getter replaces its own descriptor');
print('PROPERTY-ORDER checks='+checks+' failures=0');
