/* ES2015 replacement protocols, callback reentrancy and legacy isolation.
 * MPL 1.1/GPL 2.0/LGPL 2.1. */
var checks=0;
function check(v,name){++checks;if(!v)throw Error('RegExp replace: '+name);}
function caught(f){try{f();}catch(e){return e;}return null;}
var replace=RegExp.prototype[Symbol.replace],d=Object.getOwnPropertyDescriptor(RegExp.prototype,Symbol.replace);
check(d.writable&&d.configurable&&!d.enumerable&&replace.length===2&&replace.name==='[Symbol.replace]','metadata');
check(!replace.hasOwnProperty('prototype')&&caught(function(){new replace();}) instanceof TypeError,'nonconstructor');
check(caught(function(){replace.call(null,'a','b');}) instanceof TypeError,'null receiver');
check(caught(function(){replace.call('a','a','b');}) instanceof TypeError,'primitive receiver');
check(replace.call(/a/,'baac','x')==='bxac','first match');
check(replace.call(/a/g,'baac','x')==='bxxc','global match');
check(replace.call(/(?:)/g,'ab','-')==='-a-b-','empty global advancement');
check(replace.call(/(a)(b)?/,'xaY','$$:$&:$1:$2:$3:$01:$10:$`:$\'')==='x$:a:a::$3:a:a0:x:YY','substitution tokens');
check(replace.call(/a/,'a','$+-$0-$00')==='$+-$0-$00','modern replacement does not add legacy tokens');
var r=/a/y;r.lastIndex=1;check(replace.call(r,'ba','x')==='bx'&&r.lastIndex===2,'sticky index');
r.lastIndex=0;check(replace.call(r,'ba','x')==='ba'&&r.lastIndex===0,'sticky failure');
var seen=[],result=replace.call(/(a)(b)?/g,'a ab',function(m,a,b,p,s){'use strict';gc();seen.push([this,m,a,b,p,s]);return String(p);});
check(result==='0 2'&&seen.length===2&&seen[0][0]===undefined&&seen[0][3]===undefined&&seen[1][3]==='b'&&seen[1][4]===2&&seen[1][5]==='a ab','callback captures index source and strict receiver');
var log=[],i=0,obj={global:true,exec:function(){log.push('exec');gc();return i++<2?{0:'a',length:1,index:i-1}:null;}};
result=replace.call(obj,'aa',function(){log.push('replace');gc();return 'x';});
check(result==='xx'&&log.join()==='exec,exec,exec,replace,replace','collect all matches before replacement');
log=[];obj={exec:function(){log.push('exec');return null;}};Object.defineProperty(obj,'global',{get:function(){log.push('global');return false;}});
result=replace.call(obj,{toString:function(){log.push('input');return 'a';}},{toString:function(){log.push('replacement');return 'x';}});
check(result==='a'&&log.join()==='input,replacement,global,exec','conversion order with no matches');
var marker={};obj={exec:function(){throw marker;}};check(caught(function(){replace.call(obj,'a','x');})===marker,'exec exception');
obj.exec=function(){return 3;};check(caught(function(){replace.call(obj,'a','x');}) instanceof TypeError,'primitive exec result');
log=[];var match={};Object.defineProperty(match,'length',{get:function(){log.push('length');return 2;}});
Object.defineProperty(match,'0',{get:function(){log.push('matched');return {toString:function(){gc();log.push('matched-string');return 'a';}};}});
Object.defineProperty(match,'index',{get:function(){log.push('index');return {valueOf:function(){gc();log.push('index-number');return 0;}};}});
Object.defineProperty(match,'1',{get:function(){log.push('capture');return {toString:function(){gc();log.push('capture-string');return 'cap';}};}});
obj.exec=function(){return match;};result=replace.call(obj,'a','$1');
check(result==='cap'&&log.join()==='length,matched,matched-string,index,index-number,capture,capture-string','result access and conversion order');
i=0;obj={global:true,exec:function(){return i++<2?{0:'a',length:1,index:0}:null;}};seen=0;
result=replace.call(obj,'ab',function(){++seen;return 'x';});
check(result==='xb'&&seen===2,'overlapping results still invoke callbacks');
obj={exec:function(){return {0:'long',length:1,index:100};}};
check(replace.call(obj,'ab','$&:$\'')==='ablong:','index clamps and oversized match suffix');
obj.exec=function(){return {0:'a',length:1,index:-100};};check(replace.call(obj,'ab','x')==='xb','negative index clamps');
seen=[];obj={global:true,unicode:true,exec:function(){seen.push(this.lastIndex);return seen.length<3?{0:'',length:1,index:this.lastIndex}:null;}};
check(replace.call(obj,'\ud83d\ude00x','-')==='-\ud83d\ude00-x'&&seen.join()==='0,2,3','custom Unicode advancement');
obj={exec:function(){return {0:'a',length:2,index:0,1:Symbol('capture')};}};
check(caught(function(){replace.call(obj,'a','$1');}) instanceof TypeError,'symbol capture conversion');
check(caught(function(){replace.call(/a/,'a',function(){return Symbol('replacement');});}) instanceof TypeError,'symbol callback result');
obj={exec:function(){return {0:'',length:1,index:0};}};
var huge=new Array(2001).join('x');check(replace.call(obj,'a',huge)===huge+'a','checked output buffer growth');
var receiver={},replacement={},pattern={};pattern[Symbol.replace]=function(s,r){'use strict';gc();return this===pattern&&s===receiver&&r===replacement;};
check(String.prototype.replace.call(receiver,pattern,replacement),'String raw protocol dispatch');
Object.defineProperty(Number.prototype,Symbol.replace,{configurable:true,get:function(){'use strict';check(this===7,'primitive getter receiver');return function(s,r){'use strict';gc();return this===7&&s===receiver&&r===replacement;};}});
check(String.prototype.replace.call(receiver,7,replacement),'primitive method receiver');delete Number.prototype[Symbol.replace];
check(caught(function(){String.prototype.replace.call(null,pattern,replacement);}) instanceof TypeError,'String null receiver');
pattern={};pattern[Symbol.replace]=3;check(caught(function(){'a'.replace(pattern,'b');}) instanceof TypeError,'String noncallable method');
log=[];result=String.prototype.replace.call({toString:function(){log.push('input');return 'a';}},{toString:function(){log.push('search');return 'z';}},{toString:function(){log.push('replacement');return 'b';}});
check(result==='a'&&log.join()==='input,search,replacement','fallback conversion even without match');
check('aba'.replace('a','x')==='xba'&&'a'.replace('','x')==='xa','fallback first and empty search');
check('abc'.replace('b','$$:$&:$`:$\':$1:$+')==='a$:b:a:c:$1:$+c','fallback substitution');
seen=[];check('aba'.replace('b',function(m,p,s){'use strict';gc();seen=[this,m,p,s];return {toString:function(){gc();return 'x';}};})==='axa'&&seen[0]===undefined&&seen[1]==='b'&&seen[2]===1&&seen[3]==='aba','fallback callback receiver and conversion');
r=/a/;r[Symbol.replace]=null;check('x/a/y'.replace(r,'b')==='xby','null protocol converts regexp to string');
print('ES6-REGEXP-REPLACE checks='+checks+' failures=0');
