#!/usr/bin/env python3
"""Generate ES2015 identifier properties from the pinned Unicode data."""
import argparse
import hashlib
from pathlib import Path

DIGEST = '09c928886a178fcafd93c29e4bd59073a058e5a100b716d425cb563ab50f68c9'

def generate(directory):
    data = (directory / 'DerivedCoreProperties.txt').read_bytes()
    if hashlib.sha256(data).hexdigest() != DIGEST:
        raise ValueError('Unicode 18.0.0 checksum mismatch')
    properties = {'ID_Start': [], 'ID_Continue': []}
    for line in data.decode('utf-8').splitlines():
        fields = [s.strip() for s in line.split('#', 1)[0].split(';')]
        if len(fields) < 2 or fields[1] not in properties:
            continue
        ends = fields[0].split('..')
        properties[fields[1]].append((int(ends[0], 16), int(ends[-1], 16)))
    lines = ['/* Generated by unicode/generate-identifiers.py; do not edit.',
             ' * Unicode 18.0.0 data: Copyright (c) 1991-2026 Unicode, Inc.',
             ' * Distributed under Unicode License V3; see unicode/LICENSE.txt. */']
    for prop, ranges in properties.items():
        merged = []
        for lo, hi in sorted(ranges):
            assert 0 <= lo <= hi <= 0x10ffff
            if merged and lo <= merged[-1][1] + 1:
                merged[-1] = (merged[-1][0], max(hi, merged[-1][1]))
            else:
                merged.append((lo, hi))
        lines.append('static const IdentifierRange identifier%s[] = {' % prop)
        lines.extend('    {0x%x, 0x%x},' % r for r in merged)
        lines.append('};')
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ucd', required=True, type=Path)
    parser.add_argument('--output', required=True, type=Path)
    args = parser.parse_args()
    args.output.write_text(generate(args.ucd))
