#!/usr/bin/env python3
"""Generate private normalization tables from checksum-pinned Unicode 18.0.0."""
import argparse
import functools
import hashlib
from pathlib import Path

HASHES = {
    'UnicodeData.txt': '0736451de439ae7baf1425136617da495e09ee5afbe6e394374db7009ea08950',
    'DerivedNormalizationProps.txt': '98ac7f67d985fe781e317f6182e885e94cabb0c314769e6dd73e48b226931ccd',
}


def generate(directory):
    texts = {}
    for name, digest in HASHES.items():
        data = (directory / name).read_bytes()
        if hashlib.sha256(data).hexdigest() != digest:
            raise ValueError('Unicode 18.0.0 checksum mismatch: ' + name)
        texts[name] = data.decode('utf-8')
    classes, mappings = {}, {}
    for line in texts['UnicodeData.txt'].splitlines():
        fields = line.split(';')
        point = int(fields[0], 16)
        combining = int(fields[3])
        mapping = fields[5].split()
        if fields[1].endswith(', First>') or fields[1].endswith(', Last>'):
            assert not combining and not mapping
        if combining:
            classes[point] = combining
        if mapping:
            compatibility = mapping[0].startswith('<')
            if compatibility:
                mapping = mapping[1:]
            mappings[point] = compatibility, tuple(int(value, 16) for value in mapping)
    excluded = set()
    for line in texts['DerivedNormalizationProps.txt'].splitlines():
        fields = line.split('#', 1)[0].strip().split(';')
        if len(fields) < 2 or fields[1].strip() != 'Full_Composition_Exclusion':
            continue
        interval = fields[0].strip().split('..')
        first, last = int(interval[0], 16), int(interval[-1], 16)
        excluded.update(range(first, last + 1))

    @functools.lru_cache(None)
    def decompose(point, compatibility):
        # Hangul decompositions are algorithmic in the runtime.
        if 0xac00 <= point <= 0xd7a3:
            index = point - 0xac00
            result = (0x1100 + index // 588, 0x1161 + index % 588 // 28)
            return result + ((0x11a7 + index % 28,) if index % 28 else ())
        mapping = mappings.get(point)
        if mapping is None or mapping[0] and not compatibility:
            return (point,)
        return tuple(child for component in mapping[1]
                     for child in decompose(component, compatibility))

    pool, offsets, entries = [], {}, []
    def save(sequence, point):
        if sequence == (point,):
            return 0, 0
        if sequence not in offsets:
            offsets[sequence] = len(pool)
            pool.extend(sequence)
        return offsets[sequence], len(sequence)
    for point in sorted(mappings):
        canonical = save(decompose(point, False), point)
        compatibility = save(decompose(point, True), point)
        assert canonical[1] <= 255 and compatibility[1] <= 255
        entries.append((point, canonical[0], compatibility[0], canonical[1], compatibility[1]))
    pairs = []
    for point, (compatibility, mapping) in mappings.items():
        if not compatibility and len(mapping) == 2 and point not in excluded:
            assert classes.get(mapping[0], 0) == 0
            pairs.append((mapping[0], mapping[1], point))
    pairs.sort()
    assert len({pair[:2] for pair in pairs}) == len(pairs)
    ranges = []
    for point, combining in sorted(classes.items()):
        if ranges and ranges[-1][1] + 1 == point and ranges[-1][2] == combining:
            ranges[-1] = ranges[-1][0], point, combining
        else:
            ranges.append((point, point, combining))
    lines = ['/* Generated by generate-normalization.py; do not edit.',
             ' * Unicode 18.0.0 data: Copyright (c) 1991-2026 Unicode, Inc.',
             ' * Distributed under Unicode License V3; see unicode/LICENSE.txt.',
             ' * Source: https://www.unicode.org/Public/18.0.0/ucd/',
             ' */', '#ifndef jsnormalization_data_h___',
             '#define jsnormalization_data_h___', '']
    lines += ['/* ' + name + ' SHA-256: ' + digest + ' */' for name, digest in HASHES.items()]
    lines += ['', 'static const uint32 normalizationSequence[] = {']
    for start in range(0, len(pool), 8):
        lines.append('    ' + ', '.join('0x%x' % point for point in pool[start:start+8]) + ',')
    lines += ['};', '', 'static const NormalizationMapping normalizationMappings[] = {']
    lines += ['    {0x%x, %d, %d, %d, %d},' % entry for entry in entries]
    lines += ['};', '', 'static const CombiningRange normalizationClasses[] = {']
    lines += ['    {0x%x, 0x%x, %d},' % entry for entry in ranges]
    lines += ['};', '', 'static const CompositionPair normalizationPairs[] = {']
    lines += ['    {0x%x, 0x%x, 0x%x},' % entry for entry in pairs]
    lines += ['};', '', '#endif', '']
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ucd', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    args.output.write_text(generate(args.ucd), encoding='ascii')


if __name__ == '__main__':
    main()
