#!/usr/bin/env python3
"""Generate private modern JavaScript casing tables from Unicode 18.0.0."""
import argparse
import hashlib
from pathlib import Path
HASHES = {
    'UnicodeData.txt': '0736451de439ae7baf1425136617da495e09ee5afbe6e394374db7009ea08950',
    'SpecialCasing.txt': '8538dea57c184f1ef3783885ea79677b10f6efa06423717157e63712f14d1ad2',
    'DerivedCoreProperties.txt': '09c928886a178fcafd93c29e4bd59073a058e5a100b716d425cb563ab50f68c9',
}
def generate(directory):
    texts = {}
    for name, digest in HASHES.items():
        data = (directory / name).read_bytes()
        if hashlib.sha256(data).hexdigest() != digest:
            raise ValueError('Unicode 18.0.0 checksum mismatch: ' + name)
        texts[name] = data.decode('utf-8')
    lower, upper = {}, {}
    for line in texts['UnicodeData.txt'].splitlines():
        fields = line.split(';'); point = int(fields[0], 16)
        for mappings, field in [(upper, 12), (lower, 13)]:
            if fields[field]: mappings[point] = (int(fields[field], 16),)
    conditional = []
    for line in texts['SpecialCasing.txt'].splitlines():
        fields = [s.strip() for s in line.split('#', 1)[0].split(';')]
        if len(fields) < 5: continue
        point = int(fields[0], 16)
        if fields[4]:
            if not any(tag in fields[4].split() for tag in ['tr', 'az', 'lt']):
                conditional.append((point, fields[1], fields[4]))
            continue
        for mappings, field in [(lower, 1), (upper, 3)]:
            mappings[point] = tuple(int(v, 16) for v in fields[field].split())
    # The only language-independent conditional mapping is handled at runtime.
    assert conditional == [(0x03a3, '03C2', 'Final_Sigma')], conditional
    properties = {'Cased': [], 'Case_Ignorable': []}
    for line in texts['DerivedCoreProperties.txt'].splitlines():
        fields = [s.strip() for s in line.split('#', 1)[0].split(';')]
        if len(fields) < 2 or fields[1] not in properties: continue
        limits = fields[0].split('..')
        properties[fields[1]].append((int(limits[0], 16), int(limits[-1], 16)))
    pool, offsets = [], {}
    def save(sequence, point):
        if sequence == (point,): return 0, 0
        if sequence not in offsets:
            offsets[sequence] = len(pool); pool.extend(sequence)
        assert len(sequence) <= 255
        return offsets[sequence], len(sequence)
    entries = []
    for point in sorted(lower.keys() | upper.keys()):
        lo = save(lower.get(point, (point,)), point)
        up = save(upper.get(point, (point,)), point)
        if lo[1] or up[1]: entries.append((point, lo[0], up[0], lo[1], up[1]))
    lines = ['/* Generated by generate-casing.py; do not edit.',
             ' * Unicode 18.0.0 data: Copyright (c) 1991-2026 Unicode, Inc.',
             ' * Distributed under Unicode License V3; see unicode/LICENSE.txt. */',
             'static const uint32 casingSequences[] = {']
    for i in range(0, len(pool), 8): lines.append('    ' + ', '.join('0x%x' % p for p in pool[i:i+8]) + ',')
    lines.extend(['};', 'static const CasingMapping casingMappings[] = {'])
    lines.extend('    {0x%x, %u, %u, %u, %u},' % e for e in entries)
    lines.append('};')
    for name, ranges in properties.items():
        merged = []
        for first, last in sorted(ranges):
            if merged and first <= merged[-1][1] + 1:
                merged[-1] = merged[-1][0], max(merged[-1][1], last)
            else: merged.append((first, last))
        lines.append('static const CasingRange casing%s[] = {' % name)
        lines.extend('    {0x%x, 0x%x},' % r for r in merged)
        lines.append('};')
    return '\n'.join(lines) + '\n'
if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ucd', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    args.output.write_text(generate(args.ucd))
