#!/usr/bin/env python3
"""Generate Unicode 18.0.0 simple/common folding for ES2015 Unicode regexps."""
import argparse
import hashlib
from pathlib import Path

SHA256 = 'a004797658a457bec4dc11683e39f69249ea3b595b752dbea6721c4c9f587b0d'

def mappings(directory):
    data = (directory / 'CaseFolding.txt').read_bytes()
    if hashlib.sha256(data).hexdigest() != SHA256:
        raise ValueError('Unicode 18.0.0 CaseFolding.txt checksum mismatch')
    result = []
    for line in data.decode('utf-8').splitlines():
        fields = [part.strip() for part in line.split('#', 1)[0].split(';')]
        if len(fields) < 3 or fields[1] not in ('C', 'S'):
            continue
        target = fields[2].split()
        assert len(target) == 1
        result.append((int(fields[0], 16), int(target[0], 16)))
    assert len(result) == 1533 and result == sorted(result)
    return result

def generate(directory):
    lines = ['/* Generated by unicode/generate-regexp-casefold.py; do not edit.',
             ' * Unicode 18.0.0 data: Copyright (c) 1991-2026 Unicode, Inc.',
             ' * Distributed under Unicode License V3; see unicode/LICENSE.txt. */',
             'static const struct { uint32 from, to; } regexpCaseFolds[] = {']
    lines.extend('    {0x%X,0x%X},' % pair for pair in mappings(directory))
    return '\n'.join(lines + ['};', ''])

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--ucd', type=Path, required=True)
    parser.add_argument('--output', type=Path, required=True)
    args = parser.parse_args()
    args.output.write_text(generate(args.ucd))
